version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/websitedb
      SPRING_DATASOURCE_USERNAME: gunnar
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      TMBD_KEY: f243c7df98509f0108668fb5705b2844
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: websitedb
      POSTGRES_USER: gunnar
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
